
const initialCards = {
  swahili: [
    { id: 1, word: 'Hello', translation: 'Habari', category: 'greetings' },
    { id: 2, word: 'I respect you (formal greeting)', translation: 'Shikamoo', category: 'greetings' },
    { id: 3, word: 'I accept your respect (response to Shikamoo)', translation: 'Marahaba', category: 'greetings' },
    { id: 4, word: 'How are you?', translation: 'Hujambo', category: 'greetings' },
    { id: 5, word: 'I’m fine (response to Hujambo)', translation: 'Sijambo', category: 'greetings' },
    { id: 6, word: 'Hello (informal)', translation: 'Jambo', category: 'greetings' },
    { id: 7, word: 'Peaceful', translation: 'Salama', category: 'greetings' },
    { id: 8, word: 'Welcome', translation: 'Karibu', category: 'greetings' },
    { id: 9, word: 'Goodbye', translation: 'Kwa heri', category: 'greetings' },
    { id: 10, word: 'Sorry (for sympathy)', translation: 'Pole', category: 'greetings' },
    { id: 11, word: 'Excuse me / I\'m sorry', translation: 'Samahani', category: 'greetings' },
    { id: 12, word: 'Please', translation: 'Tafadhali', category: 'greetings' },
    { id: 13, word: 'Thank you', translation: 'Asante', category: 'greetings' },
    { id: 14, word: 'Thank you very much', translation: 'Asante sana', category: 'greetings' },
    { id: 15, word: 'Goodbye (to a group)', translation: 'Kwa herini', category: 'greetings' },

    { id: 16, word: 'Hour', translation: 'Saa', category: 'time' },
    { id: 17, word: 'What time?', translation: 'Saa ngapi?', category: 'time' },
    { id: 18, word: 'Morning', translation: 'Asubuhi', category: 'time' },
    { id: 19, word: 'Afternoon', translation: 'Mchana', category: 'time' },
    { id: 20, word: 'Evening', translation: 'Jioni', category: 'time' },
    { id: 21, word: 'Night', translation: 'Usiku', category: 'time' },
    { id: 22, word: 'Today', translation: 'Leo', category: 'time' },
    { id: 23, word: 'Yesterday', translation: 'Jana', category: 'time' },
    { id: 24, word: 'Tomorrow', translation: 'Kesho', category: 'time' },
    { id: 25, word: 'Day', translation: 'Siku', category: 'time' },
    { id: 26, word: 'Week', translation: 'Wiki', category: 'time' },
    { id: 27, word: 'Month', translation: 'Mwezi', category: 'time' },
    { id: 28, word: 'Year', translation: 'Mwaka', category: 'time' },
    { id: 29, word: 'Minute', translation: 'Dakika', category: 'time' },
    { id: 30, word: 'Second', translation: 'Sekunde', category: 'time' },

    { id: 31, word: 'School', translation: 'Shule', category: 'places' },
    { id: 32, word: 'Market', translation: 'Soko', category: 'places' },
    { id: 33, word: 'Hospital', translation: 'Hospitali', category: 'places' },
    { id: 34, word: 'Church', translation: 'Kanisa', category: 'places' },
    { id: 35, word: 'City', translation: 'Mji', category: 'places' },
    { id: 36, word: 'House', translation: 'Nyumba', category: 'places' },
    { id: 37, word: 'At the market', translation: 'Sokoni', category: 'places' },
    { id: 38, word: 'Street', translation: 'Mtaa', category: 'places' },
    { id: 39, word: 'Mainland', translation: 'Bara', category: 'places' },
    { id: 40, word: 'Ocean', translation: 'Bahari', category: 'places' },
    { id: 41, word: 'Country', translation: 'Nchi', category: 'places' },
    { id: 42, word: 'Village', translation: 'Kijiji', category: 'places' },
    { id: 43, word: 'Bridge', translation: 'Daraja', category: 'places' },
    { id: 44, word: 'Lake', translation: 'Ziwa', category: 'places' },
    { id: 45, word: 'River', translation: 'Mto', category: 'places' },  

    { id: 46, word: 'Book', translation: 'Kitabu', category: 'things' },
    { id: 47, word: 'Pen', translation: 'Kalamu', category: 'things' },
    { id: 48, word: 'Cup', translation: 'Kikombe', category: 'things' },
    { id: 49, word: 'Water', translation: 'Maji', category: 'things' },
    { id: 50, word: 'Table', translation: 'Meza', category: 'things' },
    { id: 51, word: 'Chair', translation: 'Kiti', category: 'things' },
    { id: 52, word: 'Computer', translation: 'Kompyuta', category: 'things' },
    { id: 53, word: 'Phone', translation: 'Simu', category: 'things' },
    { id: 54, word: 'Car', translation: 'Gari', category: 'things' },
    { id: 55, word: 'Money', translation: 'Pesa', category: 'things' },
    { id: 56, word: 'Food', translation: 'Chakula', category: 'things' },
    { id: 57, word: 'Drum', translation: 'Ngoma', category: 'things' },
    { id: 58, word: 'Clothes', translation: 'Nguo', category: 'things' },
    { id: 59, word: 'Bag', translation: 'Mfuko', category: 'things' },
    { id: 60, word: 'Spoon', translation: 'Kijiko', category: 'things' },

    { id: 61, word: 'Teacher', translation: 'Mwalimu', category: 'people' },
    { id: 62, word: 'Student', translation: 'Mwanafunzi', category: 'people' },
    { id: 63, word: 'Mother', translation: 'Mama', category: 'people' },
    { id: 64, word: 'Father', translation: 'Baba', category: 'people' },
    { id: 65, word: 'Brother', translation: 'Kaka', category: 'people' },
    { id: 66, word: 'Sister', translation: 'Dada', category: 'people' },
    { id: 67, word: 'Friend', translation: 'Rafiki', category: 'people' },
    { id: 68, word: 'Elder', translation: 'Mzee', category: 'people' },
    { id: 69, word: 'Leader', translation: 'Kiongozi', category: 'people' },
    { id: 70, word: 'Child', translation: 'Mtoto', category: 'people' },
    { id: 71, word: 'Pastor', translation: 'Mchungaji', category: 'people' },
    { id: 72, word: 'Police', translation: 'Polisi', category: 'people' },
    { id: 73, word: 'Driver', translation: 'Dereva', category: 'people' },
    { id: 74, word: 'Doctor', translation: 'Daktari', category: 'people' },
    { id: 75, word: 'Participant', translation: 'Mshiriki', category: 'people' },  

    { id: 76, word: 'Tree', translation: 'Mti', category: 'nature' },
    { id: 77, word: 'Flower', translation: 'Maua', category: 'nature' },
    { id: 78, word: 'Cloud', translation: 'Wingu', category: 'nature' },
    { id: 79, word: 'Sun', translation: 'Jua', category: 'nature' },
    { id: 80, word: 'Moon', translation: 'Mwezi', category: 'nature' },
    { id: 81, word: 'Rain', translation: 'Mvua', category: 'nature' },
    { id: 82, word: 'Wind', translation: 'Upepo', category: 'nature' },
  ],
  french: [
    { id: 1, word: 'Hello', translation: 'Bonjour', category: 'greetings' },
    { id: 2, word: 'How are you?', translation: 'Comment ça va?', category: 'greetings' },
    { id: 3, word: 'I’m fine', translation: 'Je vais bien', category: 'greetings' },
    { id: 4, word: 'Goodbye', translation: 'Au revoir', category: 'greetings' },
    { id: 5, word: 'Welcome', translation: 'Bienvenue', category: 'greetings' },
    { id: 6, word: 'Sorry', translation: 'Désolé', category: 'greetings' },
    { id: 7, word: 'Excuse me', translation: 'Excusez-moi', category: 'greetings' },
    { id: 8, word: 'Please', translation: 'S\'il vous plaît', category: 'greetings' },
    { id: 9, word: 'Thank you', translation: 'Merci', category: 'greetings' },
    { id: 10, word: 'Thank you very much', translation: 'Merci beaucoup', category: 'greetings' },
    { id: 11, word: 'Good morning', translation: 'Bonjour', category: 'greetings' },
    { id: 12, word: 'Good evening', translation: 'Bonsoir', category: 'greetings' },
    { id: 13, word: 'Good night', translation: 'Bonne nuit', category: 'greetings' },
    { id: 14, word: 'See you soon', translation: 'À bientôt', category: 'greetings' },
    { id: 15, word: 'Take care', translation: 'Prends soin de toi', category: 'greetings' },
 
    { id: 16, word: 'Hour', translation: 'Heure', category: 'time' },
    { id: 17, word: 'What time?', translation: 'Quelle heure?', category: 'time' },
    { id: 18, word: 'Morning', translation: 'Matin', category: 'time' },
    { id: 19, word: 'Afternoon', translation: 'Après-midi', category: 'time' },
    { id: 20, word: 'Evening', translation: 'Soir', category: 'time' },
    { id: 21, word: 'Night', translation: 'Nuit', category: 'time' },
    { id: 22, word: 'Today', translation: 'Aujourd\'hui', category: 'time' },
    { id: 23, word: 'Yesterday', translation: 'Hier', category: 'time' },
    { id: 24, word: 'Tomorrow', translation: 'Demain', category: 'time' },
    { id: 25, word: 'Day', translation: 'Jour', category: 'time' },
    { id: 26, word: 'Week', translation: 'Semaine', category: 'time' },
    { id: 27, word: 'Month', translation: 'Mois', category: 'time' },
    { id: 28, word: 'Year', translation: 'Année', category: 'time' },
    { id: 29, word: 'Minute', translation: 'Minute', category: 'time' },
    { id: 30, word: 'Second', translation: 'Seconde', category: 'time' },
   
    { id: 31, word: 'School', translation: 'École', category: 'places' },
    { id: 32, word: 'Market', translation: 'Marché', category: 'places' },
    { id: 33, word: 'Hospital', translation: 'Hôpital', category: 'places' },
    { id: 34, word: 'Church', translation: 'Église', category: 'places' },
    { id: 35, word: 'City', translation: 'Ville', category: 'places' },
    { id: 36, word: 'House', translation: 'Maison', category: 'places' },
    { id: 37, word: 'At the market', translation: 'Au marché', category: 'places' },
    { id: 38, word: 'Street', translation: 'Rue', category: 'places' },
    { id: 39, word: 'Mainland', translation: 'Continent', category: 'places' },
    { id: 40, word: 'Ocean', translation: 'Océan', category: 'places' },
    { id: 41, word: 'Country', translation: 'Pays', category: 'places' },
    { id: 42, word: 'Village', translation: 'Village', category: 'places' },
    { id: 43, word: 'Bridge', translation: 'Pont', category: 'places' },
    { id: 44, word: 'Lake', translation: 'Lac', category: 'places' },
    { id: 45, word: 'River', translation: 'Rivière', category: 'places' },
    
    { id: 46, word: 'Book', translation: 'Livre', category: 'things' },
    { id: 47, word: 'Pen', translation: 'Stylo', category: 'things' },
    { id: 48, word: 'Cup', translation: 'Tasse', category: 'things' },
    { id: 49, word: 'Water', translation: 'Eau', category: 'things' },
    { id: 50, word: 'Table', translation: 'Table', category: 'things' },
    { id: 51, word: 'Chair', translation: 'Chaise', category: 'things' },
    { id: 52, word: 'Computer', translation: 'Ordinateur', category: 'things' },
    { id: 53, word: 'Phone', translation: 'Téléphone', category: 'things' },
    { id: 54, word: 'Car', translation: 'Voiture', category: 'things' },
    { id: 55, word: 'Money', translation: 'Argent', category: 'things' },
    { id: 56, word: 'Food', translation: 'Nourriture', category: 'things' },
    { id: 57, word: 'Drum', translation: 'Tambour', category: 'things' },
    { id: 58, word: 'Clothes', translation: 'Vêtements', category: 'things' },
    { id: 59, word: 'Bag', translation: 'Sac', category: 'things' },
    { id: 60, word: 'Spoon', translation: 'Cuillère', category: 'things' },
   
    { id: 61, word: 'Teacher', translation: 'Enseignant', category: 'people' },
    { id: 62, word: 'Student', translation: 'Étudiant', category: 'people' },
    { id: 63, word: 'Mother', translation: 'Mère', category: 'people' },
    { id: 64, word: 'Father', translation: 'Père', category: 'people' },
    { id: 65, word: 'Brother', translation: 'Frère', category: 'people' },
    { id: 66, word: 'Sister', translation: 'Sœur', category: 'people' },
    { id: 67, word: 'Friend', translation: 'Ami', category: 'people' },
    { id: 68, word: 'Elder', translation: 'Aîné', category: 'people' },
    { id: 69, word: 'Leader', translation: 'Chef', category: 'people' },
    { id: 70, word: 'Child', translation: 'Enfant', category: 'people' },
    { id: 71, word: 'Pastor', translation: 'Pasteur', category: 'people' },
    { id: 72, word: 'Police', translation: 'Police', category: 'people' },
    { id: 73, word: 'Driver', translation: 'Chauffeur', category: 'people' },
    { id: 74, word: 'Doctor', translation: 'Docteur', category: 'people' },
    { id: 75, word: 'Participant', translation: 'Participant', category: 'people' },

    { id: 76, word: 'Tree', translation: 'Arbre', category: 'nature' },
    { id: 77, word: 'Flower', translation: 'Fleur', category: 'nature' },
    { id: 78, word: 'Cloud', translation: 'Nuage', category: 'nature' },
    { id: 79, word: 'Sun', translation: 'Soleil', category: 'nature' },
    { id: 80, word: 'Moon', translation: 'Lune', category: 'nature' },
    { id: 81, word: 'Rain', translation: 'Pluie', category: 'nature' },
    { id: 82, word: 'Wind', translation: 'Vent', category: 'nature' }
  ],
chinese: [
    { id: 1, word: 'Hello', translation: '你好 (Nǐ hǎo)', category: 'greetings' },
    { id: 2, word: 'How are you?', translation: '你好吗? (Nǐ hǎo ma?)', category: 'greetings' },
    { id: 3, word: 'I’m fine', translation: '我很好 (Wǒ hěn hǎo)', category: 'greetings' },
    { id: 4, word: 'Goodbye', translation: '再见 (Zàijiàn)', category: 'greetings' },
    { id: 5, word: 'Welcome', translation: '欢迎 (Huānyíng)', category: 'greetings' },
    { id: 6, word: 'Sorry', translation: '对不起 (Duìbuqǐ)', category: 'greetings' },
    { id: 7, word: 'Excuse me', translation: '请问 (Qǐngwèn)', category: 'greetings' },
    { id: 8, word: 'Please', translation: '请 (Qǐng)', category: 'greetings' },
    { id: 9, word: 'Thank you', translation: '谢谢 (Xièxiè)', category: 'greetings' },
    { id: 10, word: 'Thank you very much', translation: '非常感谢 (Fēicháng gǎnxiè)', category: 'greetings' },
  
    { id: 11, word: 'Hour', translation: '小时 (Xiǎoshí)', category: 'time' },
    { id: 12, word: 'Minute', translation: '分钟 (Fēnzhōng)', category: 'time' },
    { id: 13, word: 'Second', translation: '秒 (Miǎo)', category: 'time' },
    { id: 14, word: 'Day', translation: '天 (Tiān)', category: 'time' },
    { id: 15, word: 'Week', translation: '星期 (Xīngqī)', category: 'time' },
    { id: 16, word: 'Month', translation: '月 (Yuè)', category: 'time' },
    { id: 17, word: 'Year', translation: '年 (Nián)', category: 'time' },
    { id: 18, word: 'Today', translation: '今天 (Jīntiān)', category: 'time' },
    { id: 19, word: 'Tomorrow', translation: '明天 (Míngtiān)', category: 'time' },
    { id: 20, word: 'Yesterday', translation: '昨天 (Zuótiān)', category: 'time' },
   
    { id: 21, word: 'School', translation: '学校 (Xuéxiào)', category: 'places' },
    { id: 22, word: 'Home', translation: '家 (Jiā)', category: 'places' },
    { id: 23, word: 'Office', translation: '办公室 (Bàngōngshì)', category: 'places' },
    { id: 24, word: 'Restaurant', translation: '餐厅 (Cāntīng)', category: 'places' },
    { id: 25, word: 'Hospital', translation: '医院 (Yīyuàn)', category: 'places' },
    { id: 26, word: 'Park', translation: '公园 (Gōngyuán)', category: 'places' },
    { id: 27, word: 'Market', translation: '市场 (Shìchǎng)', category: 'places' },
    { id: 28, word: 'City', translation: '城市 (Chéngshì)', category: 'places' },
    { id: 29, word: 'Airport', translation: '机场 (Jīchǎng)', category: 'places' },
    { id: 30, word: 'Hotel', translation: '酒店 (Jiǔdiàn)', category: 'places' },
    
    { id: 31, word: 'Man', translation: '男人 (Nánrén)', category: 'people' },
    { id: 32, word: 'Woman', translation: '女人 (Nǚrén)', category: 'people' },
    { id: 33, word: 'Child', translation: '孩子 (Háizi)', category: 'people' },
    { id: 34, word: 'Friend', translation: '朋友 (Péngyǒu)', category: 'people' },
    { id: 35, word: 'Teacher', translation: '老师 (Lǎoshī)', category: 'people' },
    { id: 36, word: 'Doctor', translation: '医生 (Yīshēng)', category: 'people' },
    { id: 37, word: 'Police', translation: '警察 (Jǐngchá)', category: 'people' },
    { id: 38, word: 'Worker', translation: '工人 (Gōngrén)', category: 'people' },
    { id: 39, word: 'Student', translation: '学生 (Xuéshēng)', category: 'people' },
    { id: 40, word: 'Family', translation: '家人 (Jiārén)', category: 'people' },
  
    { id: 41, word: 'Book', translation: '书 (Shū)', category: 'things' },
    { id: 42, word: 'Pen', translation: '笔 (Bǐ)', category: 'things' },
    { id: 43, word: 'Chair', translation: '椅子 (Yǐzi)', category: 'things' },
    { id: 44, word: 'Table', translation: '桌子 (Zhuōzi)', category: 'things' },
    { id: 45, word: 'Phone', translation: '电话 (Diànhuà)', category: 'things' },
    { id: 46, word: 'Computer', translation: '电脑 (Diànnǎo)', category: 'things' },
    { id: 47, word: 'Bag', translation: '包 (Bāo)', category: 'things' },
    { id: 48, word: 'Car', translation: '汽车 (Qìchē)', category: 'things' },
    { id: 49, word: 'Shoes', translation: '鞋子 (Xiézi)', category: 'things' },
    { id: 50, word: 'Key', translation: '钥匙 (Yàoshi)', category: 'things' },
 
    { id: 51, word: 'Sun', translation: '太阳 (Tàiyáng)', category: 'nature' },
    { id: 52, word: 'Moon', translation: '月亮 (Yuèliàng)', category: 'nature' },
    { id: 53, word: 'Star', translation: '星星 (Xīngxīng)', category: 'nature' },
    { id: 54, word: 'Mountain', translation: '山 (Shān)', category: 'nature' },
    { id: 55, word: 'River', translation: '河 (Hé)', category: 'nature' },
    { id: 56, word: 'Tree', translation: '树 (Shù)', category: 'nature' },
    { id: 57, word: 'Flower', translation: '花 (Huā)', category: 'nature' },
    { id: 58, word: 'Rain', translation: '雨 (Yǔ)', category: 'nature' },
    { id: 59, word: 'Wind', translation: '风 (Fēng)', category: 'nature' },
    { id: 60, word: 'Fire', translation: '火 (Huǒ)', category: 'nature' },
  ]
};
     

export default initialCards;